[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "3.0.0-beta"
wasmer-wasi = "3.0.0-beta"
bytemuck = "1.12.1"
anyhow = "1.0.62"